@EmployeeProfile_Api_HostAddress = http://localhost:5078

GET {{EmployeeProfile_Api_HostAddress}}/
Accept: application/json

###

GET {{EmployeeProfile_Api_HostAddress}}/api/employees
Accept: application/json

###

POST {{EmployeeProfile_Api_HostAddress}}/api/employees
Content-Type: application/json

{
  "name": "Divya",
  "email": "divya@gmail.com",
  "department": "Development",
  "role": "Frontend Developer",
  "experience": "4 Years",
  "status": "Active",
  "performance": 95,
  "image": "https://i.pravatar.cc/100?img=15"
}
